// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:locale/m/:orgSlug": {
    params: {
      "locale": string;
      "orgSlug": string;
    };
  };
  "/:locale": {
    params: {
      "locale": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:locale/m/:orgSlug" | "/:locale";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/locale-menu.tsx": {
    id: "routes/locale-menu";
    page: "/:locale/m/:orgSlug";
  };
  "routes/locale-home.tsx": {
    id: "locale-home";
    page: "/:locale";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/locale-menu": typeof import("./app/routes/locale-menu.tsx");
  "locale-home": typeof import("./app/routes/locale-home.tsx");
};